"""Testing migration

Revision ID: 462916ca6075
Revises: 'b578a157cb37'
Create Date: 2025-04-09 18:48:17.106182
"""

# revision identifiers, used by Alembic.
revision = '462916ca6075'
down_revision = 'b578a157cb37'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
