"""Initial migration

Revision ID: 77c6006e7efb
Revises: '462916ca6075'
Create Date: 2025-04-10 03:57:28.987011
"""

# revision identifiers, used by Alembic.
revision = '77c6006e7efb'
down_revision = '462916ca6075'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
