"""Initial migration

Revision ID: a8b8fbd6b9a8
Revises: 'd818839bed22'
Create Date: 2025-04-10 04:37:41.958300
"""

# revision identifiers, used by Alembic.
revision = 'a8b8fbd6b9a8'
down_revision = 'd818839bed22'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
