"""Initial migration

Revision ID: b578a157cb37
Revises: 'fbce8ccc7c03'
Create Date: 2025-04-09 18:28:54.021746
"""

# revision identifiers, used by Alembic.
revision = 'b578a157cb37'
down_revision = 'fbce8ccc7c03'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
