"""Initial migration

Revision ID: d818839bed22
Revises: '77c6006e7efb'
Create Date: 2025-04-10 04:11:59.737620
"""

# revision identifiers, used by Alembic.
revision = 'd818839bed22'
down_revision = '77c6006e7efb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
