"""Initial migration

Revision ID: fbce8ccc7c03
Revises: None
Create Date: 2025-04-09 18:13:22.301733
"""

# revision identifiers, used by Alembic.
revision = 'fbce8ccc7c03'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
